### ISSUE TITLE
Also update the footer, but for that we need to update the template or either have the styling in the same repo

### ISSUE THREAD

**Issue by vaishnavi-iyer** [codeforaotearoa/open-data-tool-kit#15]

**Comment by marcus-crane** [comment]
I had a look at it earlier today with https://github.com/codeforaotearoa/odtk-style/tree/remove-leftovers/ but I did too much apparently and the tests failed (and it means the gem won't build/work)

You can try editing it in a branch then rebuilding the gem

**Comment by marcus-crane** [comment]
Might pay to merge the USWDS branch to become master too since the gem that's being required by the Gemfile is that branch, not the main master
