### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by marcus-crane** [codeforaotearoa/open-data-tool-kit#17]
Just gonna make this a single thread for errors that need fixing

**Comment by marcus-crane** [comment]
2.2 of the Step by Step upload guide has a typo just above the list of required fields

**Comment by vaishnavi-iyer** [comment]
I think we need to get someone to just proofread the whole website --- we can ask may be rochelle or cam?

**Comment by vaishnavi-iyer** [comment]
r

**Comment by vaishnavi-iyer** [comment]
accidentally clicked close
